name: Node.js CI

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        os: [
          windows-latest,
          ubuntu-latest
        ]
        node-version: [
          20.3.0
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Test project
        run: pnpm test
        env:
          TOKEN: ${{ secrets.TOKEN }}
          USER_ID: ${{ secrets.USERID }}
          SESSION_ID: ${{ secrets.SESSIONID }}
