name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        node-version: [
          18.17.x,
          20.3.0,
          21.0.0
        ]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Type checking
        run: npm run lint
      - name: Test project
        run: npm test
        env:
          TOKEN: ${{ secrets.TOKEN }}
          USER_ID: ${{ secrets.USERID }}
          SESSION_ID: ${{ secrets.SESSIONID }}
